name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us investigate.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation and sample app
          required: true
        - label: I am using the latest version of the library
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Initialize ScreenshotBlocker with...
        2. Call method...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide environment details
      value: |
        - **Library Version**: 
        - **Android Version**: 
        - **Device/Emulator**: 
        - **API Level**: 
        - **Build Tools Version**: 
        - **Gradle Version**: 
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code that reproduces the issue
      render: kotlin
      placeholder: |
        // Your code here
        ScreenshotBlocker.init(this)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Stack Trace
      description: Any relevant logs, stack traces, or error messages
      render: text
      placeholder: Paste logs here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Additional information...
    validations:
      required: false 